apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xpostgresqlinstances.azure.platformref.upbound.io
  labels:
    provider: azure
spec:
  compositeTypeRef:
    apiVersion: azure.platformref.upbound.io/v1alpha1
    kind: XPostgreSQLInstance
  resources:
  - name: postgresqlserver
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: Server
      spec:
        forProvider:
          version: "11"
          administratorLogin: psqladmin
          location: West US 2
          skuName: GP_Gen5_2
          storageMb: 5120
          sslEnforcementEnabled: true
          identity:
          - type: SystemAssigned
          # due to: https://github.com/Azure/azure-rest-api-specs/issues/9571
          infrastructureEncryptionEnabled: false
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-postgresql"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-postgresql"
    - fromFieldPath: spec.parameters.storageGB
      toFieldPath: spec.forProvider.storageMb
      transforms:
      - type: math
        math:
          multiply: 1024
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/app]
    - fromFieldPath: spec.parameters.passwordSecretRef.namespace
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.namespace
    - fromFieldPath: spec.parameters.passwordSecretRef.name
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.name
    - fromFieldPath: spec.parameters.passwordSecretRef.key
      toFieldPath: spec.forProvider.administratorLoginPasswordSecretRef.key
    connectionDetails:
        - fromConnectionSecretKey: username
        - fromConnectionSecretKey: password
        - fromConnectionSecretKey: endpoint
        - fromConnectionSecretKey: port
  # db-server vnet-rule for subnet where AKS lives in
  - name: vnetrule
    base:
      apiVersion: dbforpostgresql.azure.upbound.io/v1beta1
      kind: VirtualNetworkRule
      spec:
        forProvider:
          serverNameSelector:
            matchControllerRef: true
    patches:
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-sn-rule"
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.subnetIdSelector.matchLabels[azure.platformref.upbound.io/app]
    - fromFieldPath: spec.parameters.clusterRef.id
      toFieldPath: spec.forProvider.resourceGroupNameSelector.matchLabels[azure.platformref.upbound.io/app]
