apiVersion: azure.platformref.crossplane.io/v1alpha1
kind: Network
metadata:
  name: network
spec:
  clusterRef:
    id: platform-ref-azure #This field should match the cluster composite resource spec.id field