apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xapiteamworkspaces.ingress.platformref.upbound.io
  labels:
    provider: azure
    service: api-team-workspace
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: ingress.platformref.upbound.io/v1alpha1
    kind: XAPITeamWorkspace
  resources:
    # APIM Product for Team Workspace
    - name: apimProduct
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: ApiManagementProduct
        spec:
          forProvider:
            apiManagementName: ""  # Will be patched from shared ingress
            resourceGroupName: ""  # Will be patched from shared ingress
            displayName: ""
            state: "published"
            subscriptionRequired: true
            approvalRequired: false
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.apimProductName
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.apimProductName
          toFieldPath: spec.forProvider.displayName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.apiManagementName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.apimProductId

    # Front Door Custom Domain
    - name: frontDoorCustomDomain
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: FrontdoorCustomDomain
        spec:
          forProvider:
            frontdoorProfileId: "" # Will be patched from shared ingress
            hostName: ""
            tlsConfiguration:
              certificateType: "ManagedCertificate"
              minimumTlsVersion: "TLS12"
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.dnsPrefix
              - fromFieldPath: spec.parameters.sharedIngressRef.name
            strategy: string
            string:
              fmt: "%s.%s" # Will need DNS zone name from shared ingress
          toFieldPath: spec.forProvider.hostName
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.frontdoorProfileId
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: spec.forProvider.hostName
          toFieldPath: status.customDomain

    # Front Door Origin for APIM
    - name: frontDoorOrigin
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: FrontdoorOrigin
        spec:
          forProvider:
            frontdoorOriginGroupId: "" # Will be patched from shared ingress
            hostName: "" # Will be patched from APIM endpoint
            httpPort: 80
            httpsPort: 443
            originHostHeader: ""
            priority: 1
            weight: 1000
            enabledState: "Enabled"
            enforceCertificateNameCheck: true
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.cdnFrontdoorOriginGroupIdRef.name
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.applicationIdentifier
            strategy: string
            string:
              fmt: "%s-apim-origin"
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name

    # Front Door Route
    - name: frontDoorRoute
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: FrontdoorRoute
        spec:
          forProvider:
            frontdoorEndpointId: "" # Will be patched from shared ingress
            frontdoorOriginGroupId: "" # Will be patched from shared ingress
            frontdoorCustomDomainIds: [""] # Will reference the custom domain created above
            forwardingProtocol: "HttpsOnly"
            enabledState: "Enabled"
            httpsRedirect: true
            patternsToMatch:
              - "/*"
            supportedProtocols:
              - "Http"
              - "Https"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.cdnFrontdoorEndpointIdRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.cdnFrontdoorOriginGroupIdRef.name
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.applicationIdentifier
            strategy: string
            string:
              fmt: "%s-route"
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.id
          toFieldPath: status.frontDoorRouteId

    # DNS CNAME Record
    - name: dnsRecord
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: DnsCnameRecord
        spec:
          forProvider:
            zoneName: "" # Will be patched from shared ingress DNS zone
            resourceGroupName: "" # Will be patched from shared ingress
            ttl: 300
            record: "" # Will be patched from Front Door endpoint
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.dnsPrefix
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.sharedIngressRef.name
          toFieldPath: spec.forProvider.resourceGroupNameRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name

    # RBAC Role Assignment for Team
    - name: teamRoleAssignment
      base:
        apiVersion: azure.upjet.crossplane.io/v1alpha1
        kind: RoleAssignment
        spec:
          forProvider:
            principalId: ""
            roleDefinitionName: API Management Service Contributor
            scope: "" # Will be scoped to the APIM instance
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.teamAzureADGroupId
          toFieldPath: spec.forProvider.principalId
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.parameters.applicationIdentifier
              - fromFieldPath: spec.parameters.teamAzureADGroupId
            strategy: string
            string:
              fmt: "%s-%s-rbac"
          toFieldPath: metadata.annotations[crossplane.io/external-name]
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigName
          toFieldPath: spec.providerConfigRef.name